// Phase 2: mockCategories is now only consumed by the one-shot category
// migration (lib/queries/migrateLocalCategories.js) to seed brand-new users
// who arrive without any localStorage history. The runtime category source
// is Supabase via lib/queries/categories.js.
export const mockCategories = [
  'งาน 1',
  'งาน 2',
  'ที่บ้านให้',
  'ค่ากิน',
  'ค่าของใช้',
  'ค่าเดินทาง',
  'ค่าจิปาถะ',
  'ค่าความสุข',
  'ค่าอินเตอร์เน็ต',
  'los angeles',
  'tokyo',
];

export const mockEntries = [
  {
    id: 'e1',
    date: '2026-06-06',
    type: 'expense',
    amount: 320,
    currency: 'THB',
    fxRate: 1,
    amountThb: 320,
    category: 'ค่ากิน',
    note: 'ข้าวเที่ยง',
  },
  {
    id: 'e2',
    date: '2026-06-05',
    type: 'income',
    amount: 45000,
    currency: 'THB',
    fxRate: 1,
    amountThb: 45000,
    category: 'งาน 1',
    note: 'เงินเดือน',
  },
  {
    id: 'e3',
    date: '2026-06-04',
    type: 'expense',
    amount: 1280,
    currency: 'JPY',
    fxRate: 0.22,
    amountThb: 281.6,
    category: 'tokyo',
    note: 'ราเมง shinjuku',
  },
  {
    id: 'e4',
    date: '2026-06-03',
    type: 'expense',
    amount: 45,
    currency: 'USD',
    fxRate: 32.7,
    amountThb: 1471.5,
    category: 'los angeles',
    note: 'taxi from LAX',
  },
  {
    id: 'e5',
    date: '2026-06-02',
    type: 'expense',
    amount: 899,
    currency: 'THB',
    fxRate: 1,
    amountThb: 899,
    category: 'ค่าอินเตอร์เน็ต',
    note: 'AIS fibre',
  },
  {
    id: 'e6',
    date: '2026-05-29',
    type: 'expense',
    amount: 2400,
    currency: 'THB',
    fxRate: 1,
    amountThb: 2400,
    category: 'ค่าของใช้',
    note: 'เครื่องชงกาแฟ',
  },
  {
    id: 'e7',
    date: '2026-05-28',
    type: 'expense',
    amount: 180,
    currency: 'THB',
    fxRate: 1,
    amountThb: 180,
    category: 'ค่าเดินทาง',
    note: 'BTS เดือนนี้',
  },
  {
    id: 'e8',
    date: '2026-05-25',
    type: 'income',
    amount: 8500,
    currency: 'THB',
    fxRate: 1,
    amountThb: 8500,
    category: 'งาน 2',
    note: 'freelance milestone',
  },
  {
    id: 'e9',
    date: '2026-05-22',
    type: 'expense',
    amount: 12,
    currency: 'USD',
    fxRate: 32.7,
    amountThb: 392.4,
    category: 'ค่าความสุข',
    note: 'steam game',
  },
  {
    id: 'e10',
    date: '2026-05-20',
    type: 'expense',
    amount: 3200,
    currency: 'JPY',
    fxRate: 0.22,
    amountThb: 704,
    category: 'tokyo',
    note: 'omakase dinner',
  },
  {
    id: 'e11',
    date: '2026-05-15',
    type: 'expense',
    amount: 5000,
    currency: 'THB',
    fxRate: 1,
    amountThb: 5000,
    category: 'ที่บ้านให้',
    note: 'ค่าบ้านพ่อแม่',
  },
  {
    id: 'e12',
    date: '2026-05-10',
    type: 'expense',
    amount: 250,
    currency: 'THB',
    fxRate: 1,
    amountThb: 250,
    category: 'ค่าจิปาถะ',
    note: 'ตัดผม',
  },
];

export const mockGoals = [
  {
    id: 'g1',
    name: 'เก็บเงิน 100,000 บาท ภายใน 6 เดือน',
    targetAmount: 100000,
    currentAmount: 32500,
    deadline: '2026-12-07',
    createdAt: '2026-06-01',
  },
];
